[package]
cairo-version = "=2.10.1"
name = "erc721"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.36.0" }

[dependencies]
openzeppelin = "0.21.0"

[[target.starknet-contract]]
casm = true