name: Contracts CI

on:
  push:
    branches:
      - main
      - "**"
    paths:
      - "**"
      - "**"
  pull_request:
    branches:
      - main
      - "**"
    paths:
      - "**"
      - "**"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dojo using dojoup
        run: |
          curl -L https://install.dojoengine.org | bash
          . "$HOME/.config/.dojo/env"
          dojoup install 1.5.0
          echo "$HOME/.config/.dojo/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install Starknet Foundry for tokens
        uses: asdf-vm/actions/setup@v2

      - name: Install Starknet Foundry
        run: |
          asdf plugin add starknet-foundry
          asdf install starknet-foundry 0.39.0
          asdf global starknet-foundry 0.39.0

      - name: Build contracts
        run: |
          cd poker-texas-hold-em/contract
          sozo build

      - name: Run tests
        run: |
          cd poker-texas-hold-em/contract
          sozo test

      - name: Check formatting
        run: |
          cd poker-texas-hold-em/contract
          scarb fmt --check

      - name: Tokens
        run: |
          cd poker-texas-hold-em/tokens
          scarb build
          snforge test
          scarb fmt --check
